import { Service } from '@/server'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Server Component',
	description: 'Generated by create next app',
}

const ServerPage = async () => {
	const data = await Service.getPosts()

	return (
		<div>
			<h1 className='text-4xl font-mono py-6'>Server component</h1>
			{data && data.map(c => <p key={c.id}>{c.title}</p>)}
		</div>
	)
}

export default ServerPage
